# Generated by Django 5.1.8 on 2025-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=1, upload_to='profile_img/'),
            preserve_default=False,
        ),
    ]
