# Generated by Django 5.1.8 on 2025-04-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projectcontributor'),
            preserve_default=False,
        ),
    ]
