# Generated by Django 5.1.8 on 2025-04-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projectuser_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_users', to='portfolio.project'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
